## Yahoo Finance

The goal of this file is to import the data from Yahoo Finance

In [1]:
# import the libraries
import requests as r
from bs4 import BeautifulSoup as soup
import pandas as pd
import datetime as dt

In [2]:
# Create a function that get a "stock" and "start_date" and "end_date"

In [3]:
# Example of a URL
#url = 'https://finance.yahoo.com/quote/IWD/history?period1=1546300800&period2=1561071600&interval=1d&filter=history&frequency=1d'

In [4]:
def get_url(stock,start_date, end_date):
    # Handle Dates 
    # Yahoo start Date is 19700101
    year_start = int(start_date[0:4])
    month_start = int(start_date[4:6])
    day_start = int(start_date[-2:])
    t1 = dt.datetime(year_start, month_start, day_start, 0, 0)
    period_1 = str(int((t1-dt.datetime(1970,1,1)).total_seconds()))
    
    year_end = int(end_date[0:4])
    month_end = int(end_date[4:6])
    day_end = int(end_date[-2:])
    t2 = dt.datetime(year_end, month_end, day_end, 0, 0)
    period_2 = str(int((t2-dt.datetime(1970,1,1)).total_seconds()))
    print(period_1,period_2)
    
    # Build URL
    url = 'https://finance.yahoo.com/quote/' + stock + '/history?period1='+ period_1 +'&period2='+ period_2 + '&interval=1d&filter=history&frequency=1d'
    return url
    print(url)
    
#url = get_url()

In [14]:
# dates yyyymmdd
# the end date is exclusive
url = get_url('IWD','20181231','20190201')

1546214400 1548979200

In [15]:
# Remember the parser
data = r.get(url)
page_data = soup(data.text, 'html.parser')

table = page_data.findAll('table')[0]
df = pd.read_html(str(table))
my_table = df[0]

# Rmove rows with the Dividend atribution
my_table = my_table[~my_table['Open'].str.contains("Dividend")]

my_table

,Date,Open,High,Low,Close*,Adj Close**,Volume
0,"Jan 31, 2019",118.47,119.77,118.34,119.53,118.23,4317600
1,"Jan 30, 2019",118.14,119.28,117.66,118.80,117.50,3088300
2,"Jan 29, 2019",117.62,118.03,117.42,117.75,116.46,2855600
3,"Jan 28, 2019",117.13,117.54,116.63,117.51,116.23,8427400
4,"Jan 25, 2019",118.06,118.47,117.77,117.93,116.64,2330500
5,"Jan 24, 2019",117.05,117.48,116.64,117.31,116.03,3804300
6,"Jan 23, 2019",117.49,117.75,116.17,117.19,115.91,5500300
7,"Jan 22, 2019",117.69,117.78,116.30,116.97,115.69,11149500
8,"Jan 18, 2019",117.67,118.44,117.32,118.35,117.06,6190000
9,"Jan 17, 2019",115.52,117.18,115.52,116.80,115.53,3826900
10,"Jan 16, 2019",115.68,116.41,115.62,115.90,114.63,2317900
11,"Jan 15, 2019",114.56,115.60,114.56,115.46,114.20,2630100
12,"Jan 14, 2019",114.21,114.96,114.04,114.60,113.35,7072900
13,"Jan 11, 2019",114.42,115.09,114.16,115.09,113.83,9750400
14,"Jan 10, 2019",113.77,114.94,113.48,114.87,113.62,3227800
15,"Jan 09, 2019",114.36,114.75,113.67,114.39,113.14,2555600
16,"Jan 08, 2019",114.04,114.11,112.97,113.91,112.67,2849300
17,"Jan 07, 2019",112.36,113.85,111.98,112.99,111.76,5027700
18,"Jan 04, 2019",110.47,112.61,110.47,112.36,111.13,4648100
19,"Jan 03, 2019",110.60,110.96,109.02,109.22,108.03,4021400
20,"Jan 02, 2019",109.52,111.37,109.23,111.03,109.82,7237200
21,"Dec 31, 2018",110.63,111.05,109.70,111.05,109.84,9247500
22,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...